# Generated by Django 4.0.4 on 2022-06-06 18:28

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='mensaje',
            field=tinymce.models.HTMLField(max_length=500),
        ),
    ]
