# Generated by Django 4.0.4 on 2022-06-06 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0002_alter_mensaje_mensaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='visto',
        ),
    ]
