# Generated by Django 4.0.4 on 2022-06-05 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AplicacionPrincipal', '0003_alter_avatar_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='avatar',
            new_name='imagen',
        ),
    ]
