# Generated by Django 4.0.4 on 2022-06-06 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AplicacionPrincipal', '0006_posteo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posteo',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='posteo',
            name='imagen',
        ),
    ]
