# Generated by Django 4.0.4 on 2022-06-06 05:17

import AplicacionPrincipal.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AplicacionPrincipal', '0007_remove_posteo_descripcion_remove_posteo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteo',
            name='descripcion',
            field=models.TextField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posteo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=AplicacionPrincipal.models.filepath),
        ),
        migrations.AddField(
            model_name='posteo',
            name='subtitulo',
            field=models.TextField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
